services:
  nocamera-news:
    build: .
    container_name: nocamera-news
    ports:
      - "3010:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
